language: python

sudo: required

python:
    - "2.7"

install:
    - npm install -g bower
    - npm install
    - bower install --allow-root
    - pip install nose --user -I
    #- "pip install . -q"
    - "pip install -r requirements.txt --user --no-use-wheel --allow-external honcho --allow-unverified honcho"
    #- "python setup.py install"
    - "python setup_db.py"

language: node_js

node_js:
    - "8.4"

services:
    # for example 
    # - redis-server
    #- mysql-server

#install deps

cache:
    directories:
        - $HOME/.cache/pip

# tests
script: 
    - "nosetests tests"
