language: python

require:sudo

python:
    - "2.7"

install:
    - npm install
    - bower install
    #- "pip install . -q"
    - "pip install -r requirements.txt -q --user --no-use-wheel --allow-external honcho --allow-unverified honcho"      
    #- "python setup.py install"
    - "python setup_db.py"

language: node_js

node_js:
    - "iojs"

services:
    # for example 
    # - redis-server
    #- mysql-server

#install deps

cache:
    directories:
        - $HOME/.cache/pip

# tests
script: 
    - "nosetests tests"
