language: python

python:
    - "2.7"

install:
    #- "pip install . -q"
    - "pip install -r requirements.txt -vvv"      
    #- "python setup.py install"
    - "python setup_db.py"

language: node_js

node_js:
    - "iojs"

services:
    # for example 
    # - redis-server
    #- mysql-server

#install deps
install:
    - npm install
    - bower install

cache:
    directories:
        - $HOME/.cache/pip

# tests
script: 
    - "nosetests tests"
